# SPDX-FileCopyrightText: Copyright (c) 2018-2026 Almaz Ilaletdinov <a.ilaletdinov@yandex.ru>
# SPDX-License-Identifier: MIT
---
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'telegram_bot'
    static_configs:
      - targets: ['qbot:9091']
